### ISSUE TITLE
Can't read dates

### ISSUE THREAD

**Issue by tsouvarev** [phargogh/dbfpy3#3]
I have a problem reading dates from DBF. You use `utils.getDate`, which doesn't expect to get `bytes` as input. So, if you paste 
```python
if isinstance(date, bytes):
    date = date.decode()
```
right before `if isinstance(date, bytes):` in `utils.py:66`, dates are read. Call to `decode` seems to be ok, since there are only digits in input

**Comment by GeospatialPython** [comment]
Same problem for me.  The suggested patch works.

**Comment by phargogh** [comment]
I've added this patch.  Thanks!
